### ISSUE TITLE
Resizing images

### ISSUE THREAD

**Issue by matthias-k** [TsotsosLab/SMILER#14]
Hi @tkunic!

I'm using SMILER right now to evaluate several models to prepopulate the new version of the MIT Saliency Benchmark. As you can see on http://saliency.mit.edu/results_mit300.html, some of the classic models have been evaluated with additional parameters (column "Date tested", mainly resizing). Would it be possible to have such an option in SMILER, too? Then I could better reproduce the saliency maps of the models evaluated initially in the MIT Saliency Benchmark. Also I think especially resizing is quite important for many models (maybe even in two versions: resize the images with a scalar factor and resize the images to a fixed maximum size or fixed shape).

Best,
  Matthias

Best,
  Matthias

**Comment by cwloka** [comment]
We did not include a native resizing element in SMILER because a number of models already perform resizing, and it is not consistent across models whether or not the resizing is optional or required (eg. some of the classic models like QSS resize for speed or accuracy, but can run on different resolutions, whereas for most of the deep learning models they must resize to a specific resolution based on the expected network input). Since we couldn't think of a clean way of including a standardized resizing option which would also make clear which models resizing wouldn't work on, we opted to leave it out. However, I do agree that there are a number of models which do not natively include a resize parameter but which could easily incorporate one (eg. AIM); if you think this would be a valuable addition, we could add it as a model-specific option to each of them (in a semi-standardized SMILER way). Maybe you could send me an email with the set of models you want to have this option for?

**Comment by matthias-k** [comment]
Thank you for your answer! I think I agree with your reasoning: resizing images is a pretty complicated business in general with far to many hyperparameters (nearest, bilinear, bicubic, aspect ratio, etc). It's probably not worth to include an additional resizing parameter in individual models like AIM. I now just resized and saved images beforehand and run some models with the resized images as input images.
